### ISSUE TITLE
Tests fail with "unexpected fault address 0x117160" for aarch64

### ISSUE THREAD

**Issue by athos-ribeiro** [fortytw2/leaktest#17]
Architecture: aarch64
Golang version: 1.8.3
OS: Fedora 26

Same tests fail for other architectures randomly. Could not reproduce for those other arches though.

go test -compiler gc -ldflags '' github.com/fortytw2/leaktest
unexpected fault address 0x117160
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x117160 pc=0x117160]
goroutine 18 [running]:
runtime.throw(0x147168, 0x5)
	/usr/lib/golang/src/runtime/panic.go:596 +0x70 fp=0x4420040eb0 sp=0x4420040e90
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:297 +0x224 fp=0x4420040f00 sp=0x4420040eb0
github.com/fortytw2/leaktest.CheckTimeout.func1()
	/builddir/build/BUILDROOT/golang-github-fortytw2-leaktest-1.1.0-1.fc26.aarch64/usr/share/gocode/src/github.com/fortytw2/leaktest/leaktest.go:75 +0x38 fp=0x4420040f20 sp=0x4420040f10
github.com/fortytw2/leaktest.TestCheck(0x4420078270)
	/builddir/build/BUILDROOT/golang-github-fortytw2-leaktest-1.1.0-1.fc26.aarch64/usr/share/gocode/src/github.com/fortytw2/leaktest/leaktest_test.go:73 +0xb0 fp=0x4420040fa0 sp=0x4420040f20
testing.tRunner(0x4420078270, 0x150138)
	/usr/lib/golang/src/testing/testing.go:657 +0x84 fp=0x4420040fc0 sp=0x4420040fa0
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_arm64.s:981 +0x4 fp=0x4420040fc0 sp=0x4420040fc0
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:697 +0x240
goroutine 1 [chan receive]:
testing.(*T).Run(0x44200781a0, 0x147b6e, 0x9, 0x150138, 0x60)
	/usr/lib/golang/src/testing/testing.go:698 +0x260
testing.runTests.func1(0x44200781a0)
	/usr/lib/golang/src/testing/testing.go:882 +0x58
testing.tRunner(0x44200781a0, 0x442003fde0)
	/usr/lib/golang/src/testing/testing.go:657 +0x84
testing.runTests(0x4420086980, 0x1f1480, 0x2, 0x2, 0x14b00a)
	/usr/lib/golang/src/testing/testing.go:888 +0x260
testing.(*M).Run(0x442003ff28, 0x442003ff28)
	/usr/lib/golang/src/testing/testing.go:822 +0xe0
main.main()
	github.com/fortytw2/leaktest/_test/_testmain.go:44 +0xe0
goroutine 20 [sleep]:
time.Sleep(0x3b9aca00)
	/usr/lib/golang/src/runtime/time.go:59 +0xe8
github.com/fortytw2/leaktest.glob..func1()
	/builddir/build/BUILDROOT/golang-github-fortytw2-leaktest-1.1.0-1.fc26.aarch64/usr/share/gocode/src/github.com/fortytw2/leaktest/leaktest_test.go:25 +0x20
created by github.com/fortytw2/leaktest.TestCheck
	/builddir/build/BUILDROOT/golang-github-fortytw2-leaktest-1.1.0-1.fc26.aarch64/usr/share/gocode/src/github.com/fortytw2/leaktest/leaktest_test.go:71 +0xa4
goroutine 37 [chan receive]:
github.com/fortytw2/leaktest.glob..func2()
	/builddir/build/BUILDROOT/golang-github-fortytw2-leaktest-1.1.0-1.fc26.aarch64/usr/share/gocode/src/github.com/fortytw2/leaktest/leaktest_test.go:32 +0x48
created by github.com/fortytw2/leaktest.TestCheck
	/builddir/build/BUILDROOT/golang-github-fortytw2-leaktest-1.1.0-1.fc26.aarch64/usr/share/gocode/src/github.com/fortytw2/leaktest/leaktest_test.go:71 +0xa4
FAIL	github.com/fortytw2/leaktest	2.078s

**Comment by fortytw2** [comment]
Nice find! What other architectures have you seen this on?  

I don't have any aarch64 hardware to go dig into this with

**Comment by fortytw2** [comment]
@athos-ribeiro any updates on this?

**Comment by fortytw2** [comment]
closing due to lack of activity
